---
title: "Multithreading and Map-Reduce in Stan 2.18.0: A Minimal Example"
version: "v1 (19 Sep 2018)"
output: html_notebook
---

# Multithreading and Map-Reduce in Stan 2.18.0: A Minimal Example
## v1 (19 Sep 2018)

This is a beginner tutorial for using cmdstan with multithreading
by Richard McElreath: https://github.com/rmcelreath/cmdstan_map_rect_tutorial 

# Load packages
```{r}
library(here)
library(magrittr)
library(tidyverse)

```

# List converted from data read from github
```{r}
d <- RCurl::getURL("https://raw.githubusercontent.com/rmcelreath/cmdstan_map_rect_tutorial/master/RedcardData.csv") %>% 
  read.csv(text = ., stringsAsFactors=FALSE )
table( d$redCards )  # build a contingency table of the counts at each combination of factor levels

out_data <- d %>% 
  filter(!is.na(rater1)) %>% 
  sample_n(9999) %>% 
  select(n_redcards = redCards, n_games = games, rating = rater1) %>% 
  list()

out_data$N <- out_data[[1]] %>% 
  nrow()

library(rstan)
#options(mc.cores = parallel::detectCores() - 1) # For execution on a local, multicore CPU with excess RAM 
rstan_options(auto_write = TRUE)  # avoid recompilation of unchanged Stan programs
#Sys.setenv(LOCAL_CPPFLAGS = '-march=native') # For improved execution time

```


# Baseline example of Stan model
```{stan output.var=model_code}

data {
  int N;
  int n_redcards[N];
  int n_games[N];
  real rating[N];
}

parameters {
  vector[2] beta;
}

model{
  beta ~ normal(0,1);
  n_redcards ~ binomial_logit( n_games, beta[1] + beta[2] * to_vector(rating) );
}

```


# Fit the Stan model
```{R}

m0 <- stan(fit = model_code, data=out_data, chains = 1)

```

