---
title: "lavaan[Plot] Examples "
output: html_notebook
---

See also the more manual way to create customized *DiagrammeR* graphs and render as *Graphiviz* diagrams:
https://rstudio-pubs-static.s3.amazonaws.com/78926_5aa94ae32fae49f3a384ce885744ef4a.html


# Load packages
```{r}
library(lavaan)
library(lavaanPlot)
```

# HolzingerSwineford1939 Example
```{r}

library(lavaan)

HS.model <- ' visual  =~ x1 + x2 + x3 
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '

fit <- cfa(HS.model, data=HolzingerSwineford1939)

summary(fit, fit.measures=TRUE)

```

# Model with mediation: http://lavaan.ugent.be/tutorial/mediation.html
```{r}
set.seed(1234)
X <- rnorm(100)
M <- 0.5*X + rnorm(100)
Y <- 0.7*M + rnorm(100)
Data <- data.frame(X = X, Y = Y, M = M)
model <- ' # direct effect
             Y ~ c*X
           # mediator
             M ~ a*X
             Y ~ b*M
           # indirect effect (a*b)
             ab := a*b
           # total effect
             total := c + (a*b)
         '
fit <- sem(model, data = Data)
summary(fit)

lavaanPlot(model = fit)

lavaanPlot(model = fit, node_options = list(shape = "box", fontname = "Helvetica"), edge_options = list(color = "grey"), coefs = F)

```

# Model with groups: http://lavaan.ugent.be/tutorial/groups.html
```{r}

HS.model <- '  visual =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '
fit <- cfa(HS.model, 
           data = HolzingerSwineford1939, 
           group = "school",
#           group.equal = c("loadings")
          )
summary(fit)

lavaanPlot(model = fit, coefs = TRUE)

# double-sided edges to represent model covariances and also significance stars (BUT not showing in this eg !!!):
lavaanPlot(model = fit, 
           node_options = list(shape = "box", fontname = "Helvetica"), 
           edge_options = list(color = "grey"), coefs = TRUE, 
           covs = TRUE, stars = TRUE)

# significant standardized paths only and also significance stars (BUT not showing in this eg !!!):
lavaanPlot(model = fit,  
           node_options = list(shape = "box", fontname = "Helvetica"), 
           edge_options = list(color = "grey"), coefs = TRUE, 
           stars = TRUE)

# significant unstandardized paths
lavaanPlot(model = fit, node_options = list(shape = "box", fontname = "Helvetica"), edge_options = list(color = "grey"), coefs = TRUE, stand = FALSE)

# All paths unstandardized
lavaanPlot(model = fit, node_options = list(shape = "box", fontname = "Helvetica"), edge_options = list(color = "grey"), coefs = TRUE, stand = FALSE, sig = 1.00)

```